In [33]:
import numpy as np

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [24]:
def construct_reverse_array(n):
    np_array = np.arange(n-1, -1, -1)
    return np_array
reverse_array = construct_reverse_array(4)

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [31]:
matrix = np.diag(list(reverse_array))
print(matrix, matrix.trace(), sep = '\n')

[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]]
6


Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [41]:
left_side = np.array([[4 ,2 , 1],[1, 3, 0], [0, 5, 4]])
right_side = np.array([4, 12, -3])
result = np.linalg.solve(left_side, right_side)
print(f'x = {result[0]:.3f} y = {result[1]:.3f} z = {result[2]:.3f}')

x = 0.467 y = 3.844 z = -5.556
